version: '3.9'

services:
  frontend:
    build:
      context: ./my-todo-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app
    environment:
      - PYTHONUNBUFFERED=1

  dash:
    build:
      context: ./dash
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./dash:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend

volumes:
  sqlite_data:
